### ISSUE TITLE
Error after specifying vendrDbDSN

### ISSUE THREAD

**Issue by seanrockster** [vendrhub/vendr-documentation#111]
Hi Matt

Just installed the package and updated the vendrDbDSN, now when I browse to the Commerce section i get it an exception

An error occurred
Invalid object name 'vendrStore'.

Exception Details
Microsoft.Data.SqlClient.SqlException, Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5: Invalid object name 'vendrStore'.

`at Vendr.Infrastructure.Resiliency.PollyExecutionStrategyBase.Execute[TResult](Func`1 operation, Func`1 verifySucceeded)
   at Vendr.Core.VendrUnitOfWorkProvider.Execute[T](Boolean autoComplete, Func`2 action)
   at Vendr.Core.Services.StoreService.GetStoreSummariesFor(String userId, String[] userRoles)
   at Vendr.Extensions.StoreAnalyticsServiceExtensions.GetStoreSummariesFor(IStoreAnalyticsService service, IUser user)
   at Vendr.Umbraco.Web.Controllers.VendrStoreController.GetStoreSummariesForCurrentUser()
   at lambda_method1667(Closure, Object, Object[])
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)`

**Comment by mattbrailsford** [comment]
Did you already have orders when you switched the connection string?

**Comment by seanrockster** [comment]
No, I did however create a store, then remembered I can have a separate database. I've tried to the delete store but still I get an exception.

**Comment by seanrockster** [comment]
I've switch back to the umbraco, deleted the store, changed it to the new connection, but I get even angry exception. I checked the new db and there are no tables so obviously the migrations haven't run.

**Comment by seanrockster** [comment]
ah right ok, i've just restarted umbraco and its created the tables.
